[workspace]
members = [
  "app",
  "bootloader"
]

[patch.crates-io]
#embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf278ea1b6ce29b7908a9f93de4cbdfd7d0dea37" }
#embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf278ea1b6ce29b7908a9f93de4cbdfd7d0dea37" }
#embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf278ea1b6ce29b7908a9f93de4cbdfd7d0dea37" }
#embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf278ea1b6ce29b7908a9f93de4cbdfd7d0dea37" }
#embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf278ea1b6ce29b7908a9f93de4cbdfd7d0dea37" }
#embassy-boot = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf278ea1b6ce29b7908a9f93de4cbdfd7d0dea37" }
#embassy-boot-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf278ea1b6ce29b7908a9f93de4cbdfd7d0dea37" }
#embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf278ea1b6ce29b7908a9f93de4cbdfd7d0dea37" }

embassy-executor = { path = "../../embassy/embassy-executor" }
embassy-time = {path = "../../embassy/embassy-time"}
embassy-sync = {path = "../../embassy/embassy-sync"}
embassy-nrf = {path = "../../embassy/embassy-nrf"}
embassy-embedded-hal = {path = "../../embassy/embassy-embedded-hal"}
embassy-boot = {path = "../../embassy/embassy-boot/boot"}
embassy-boot-nrf = {path = "../../embassy/embassy-boot/nrf"}
embassy-futures = {path = "../../embassy/embassy-futures"}


#nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "3f4913f3791869fed5c8c152e9c0874658debfec" }
#nrf-softdevice-mbr = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "3f4913f3791869fed5c8c152e9c0874658debfec" }
#nrf-softdevice-s132 = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "3f4913f3791869fed5c8c152e9c0874658debfec" }
#
nrf-softdevice = { path = "../../nrf-softdevice/nrf-softdevice"}
nrf-softdevice-mbr = { path = "../../nrf-softdevice/nrf-softdevice-mbr"}
nrf-softdevice-s132 = { path = "../../nrf-softdevice/nrf-softdevice-s132"}

[profile.release]
debug = 2
